name: CI
on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '18'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Build
        run: ./gradlew build -Psnapshot --info -S --console=plain --show-version

      - name: Stop Gradle Daemon
        run: ./gradlew --stop

      - name: Cleanup Gradle Cache
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Cleanup Gradle Cache
        if: matrix.os == 'windows-latest'
        run: |
          rm -fo ~/.gradle/caches/modules-2/modules-2.lock
          rm -fo ~/.gradle/caches/modules-2/gc.properties